// <auto-generated />
using System;
using BooksPenalty.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksPenalty.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220925222306_Move users to customer")]
    partial class Moveuserstocustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BooksPenalty.Api.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16c82f36-7912-4c6b-9775-98d6c2c98e18"),
                            Author = "Herman Melville",
                            Name = "Moby-Dick",
                            Pages = 558
                        });
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.BookPenalty", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BookPenalties");
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbecf46b-c1eb-46b0-9e8d-b9a283688ba3")
                        });
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.BookPenalty", b =>
                {
                    b.HasOne("BooksPenalty.Api.Models.Book", "Book")
                        .WithMany("BookPenalties")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksPenalty.Api.Models.Customer", "Customer")
                        .WithMany("BookPenalties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.Book", b =>
                {
                    b.Navigation("BookPenalties");
                });

            modelBuilder.Entity("BooksPenalty.Api.Models.Customer", b =>
                {
                    b.Navigation("BookPenalties");
                });
#pragma warning restore 612, 618
        }
    }
}
